server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/uniadmission_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password= # NHAP_MAT_KHAU_CUA_BAN_VAO_DAY
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
