server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME:${SPRING_DATASOURCE_USERNAME}}
spring.datasource.password=${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:5173}
app.resend.api-key=${RESEND_API_KEY:}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:hethongxettuyen.uniadmission@gmail.com}
spring.mail.password=${MAIL_PASSWORD:vnlvrybnaaxhrgng}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.from=${MAIL_USERNAME:hethongxettuyen.uniadmission@gmail.com}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

upload.path=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB